sudo:
language: minimal
services:
  - docker
before_script:
  - docker --version
script:
  - docker build -t djerfy/rutorrent:${TRAVIS_COMMIT} .
  - docker volume create data
  - docker run -d --name seedbox -p 8080:8080 -v data:/data -e DEBUG=${DEBUG:-false} djerfy/rutorrent:${TRAVIS_COMMIT}
  - sleep 60
  - docker ps | grep seedbox && echo "Container running successfully"
  - curl -sL http://127.0.0.1:8080/ | grep theUILang.Loading && echo "ruTorrent running successfully"
  - docker logs seedbox
notifications:
  email:
    - djerfy@gmail.com
