sudo:
language: python
python:
  - "3.6"
services:
  - docker
jobs:
  include:
    - stage: "Build"
      name: "Build image"
      script:
        - docker build -t djerfy/rutorrent:${TRAVIS_COMMIT} .
    - stage: "Tests"
      name: "Unit tests"
      script:
        - docker volume create data
        - docker run -d --name seedbox -p 8080:8080 -v data:/data -e DEBUG=true djerfy/rutorrent=${TRAVIS_COMMIT}
        - sleep 60
        - docker ps | grep seedbox
        - curl -sL http://127.0.0.1:8080/ | grep -q theUILang.Loading && echo "ruTorrent access successfully"
        - docker logs seedbox
    - stage: "Clean"
      name: "Clean files"
      script:
        - docker stop seedbox
        - docker rm seedbox
        - docker volume rm data
