sudo: required
language: python
services:
  - docker
before_install:
  - docker --version
install:
  - docker build -t djerfy/rutorrent:${TRAVIS_COMMIT} .
script:
  - docker volume create data
  - docker run -d --name seedbox -p 8080:8080 -p 6881:6881 -v data:/data -e DEBUG=true djerfy/rutorrent:${TRAVIS_COMMIT}
  - sleep 60
  - docker ps | grep seedbox
  - docker logs -f seedbox
